import { useState } from 'react';
import { FileText, Copy, Check, TrendingUp, TrendingDown, Minus, AlertTriangle, ChevronLeft, BarChart3, Shield, Target } from 'lucide-react';
import { useSimulation } from '../../context/SimulationContext';

export function AnalystReport({ onBack }) {
  const sim = useSimulation();
  const [copied, setCopied] = useState(false);

  const pipeline = sim?.pipelineOutputs;
  const evaluation = pipeline?.evaluation_engine || {};
  const recommendation = pipeline?.recommendation_engine || {};
  const market = pipeline?.market_analyzer_agent?.market_context || {};
  const history = pipeline?.simulation_loop?.history || [];
  const finalState = pipeline?.simulation_loop?.final_state || {};
  const agentLogs = pipeline?.simulation_loop?.agent_logs || [];

  const score = evaluation.success_score || 0;
  const status = evaluation.status || 'UNKNOWN';
  const breakdown = evaluation.breakdown || {};
  const trends = evaluation.trends || {};

  const statusColor = {
    HIGH_POTENTIAL: 'text-success',
    MODERATE_POTENTIAL: 'text-warning',
    RISKY: 'text-danger',
    NOT_RECOMMENDED: 'text-danger',
  };

  const TrendIcon = ({ trend }) => {
    if (trend === 'Growing' || trend === 'Easing') return <TrendingUp size={12} className="text-success" />;
    if (trend === 'Declining' || trend === 'Intensifying') return <TrendingDown size={12} className="text-danger" />;
    return <Minus size={12} className="text-text-faint" />;
  };

  const generateMarkdown = () => {
    const lines = [
      `# Vyuha-Mind Post-Mortem Report`,
      ``,
      `## Evaluation Summary`,
      `- **Score**: ${score}/100 — ${status}`,
      `- **Assessment**: ${evaluation.summary || 'N/A'}`,
      ``,
      `## Market Breakdown`,
      `| Metric | Value | Trend |`,
      `|--------|-------|-------|`,
      `| Demand Health | ${breakdown.demand_health || 'N/A'} | ${trends.demand_trend || 'Stable'} |`,
      `| Competition | ${breakdown.competition_pressure || 'N/A'} | ${trends.competition_trend || 'Stable'} |`,
      `| Investor Confidence | ${breakdown.investor_confidence || 'N/A'} | — |`,
      `| Market Risk | ${breakdown.market_risk || 'N/A'} | — |`,
      ``,
      `## Market Context`,
      market.summary || 'No market summary available.',
      ``,
      `### Key Events`,
      ...(market.key_events || []).map(e => `- ${e}`),
      ``,
      `## Recommendation`,
      `- **Strategy**: ${recommendation.recommendation_type?.replace(/_/g, ' ') || 'N/A'}`,
      `- **Best Price**: ₹${recommendation.best_price || 'N/A'}`,
      `- **Score Improvement**: +${recommendation.score_improvement || 0} pts`,
      `- **Advice**: ${recommendation.strategic_advice || 'N/A'}`,
      ``,
      `## Agent Activity Log`,
      ...(agentLogs || []).map((log, i) => {
        const step = log.step || i + 1;
        return [
          `### Step ${step}`,
          `- Customer: ${log.customer?.sentiment || 'neutral'} (${log.customer?.execution_mode || 'deterministic'})`,
          `- Competitor: ${log.competitor?.strategy || 'monitoring'} → ${log.competitor?.action || 'none'}`,
          `- Investor: ${log.investor?.verdict || 'hold'}`,
        ].join('\n');
      }),
      ``,
      `---`,
      `*Generated by Vyuha-Mind Engine v2.0 • ${new Date().toISOString()}*`,
    ];
    return lines.join('\n');
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen bg-base text-text-main">
      {/* Header */}
      <div className="border-b border-border px-8 py-4 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="neo-btn bg-surface-raised border border-border text-text-muted hover:text-text-main px-3 py-2 text-sm rounded-lg">
            <ChevronLeft size={16} /> War Room
          </button>
          <div className="flex items-center gap-2">
            <FileText size={18} className="text-primary-light" />
            <h1 className="font-semibold text-lg">Analyst Post-Mortem</h1>
          </div>
        </div>
        <button onClick={handleCopy} className="neo-btn bg-surface-raised border border-border text-text-muted hover:text-text-main px-4 py-2 text-sm rounded-lg">
          {copied ? <><Check size={14} className="text-success" /> Copied!</> : <><Copy size={14} /> Export Markdown</>}
        </button>
      </div>

      <div className="max-w-4xl mx-auto px-8 py-10">
        {/* Hero Score */}
        <div className="glass-card p-8 mb-8 text-center">
          <div className="text-[10px] font-mono text-text-faint uppercase tracking-widest mb-3">PROBABILITY OF SUCCESS</div>
          <div className={`text-7xl font-bold font-mono ${statusColor[status] || 'text-text-main'}`}>
            {score}
            <span className="text-2xl text-text-faint">/100</span>
          </div>
          <div className={`text-sm font-mono mt-2 ${statusColor[status] || 'text-text-muted'}`}>
            {status.replace(/_/g, ' ')}
          </div>
          <p className="text-sm text-text-muted mt-4 max-w-lg mx-auto">{evaluation.summary}</p>
        </div>

        {/* Breakdown Grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8 stagger-children">
          {[
            { icon: Target, label: 'Demand', value: breakdown.demand_health, trend: trends.demand_trend },
            { icon: Shield, label: 'Competition', value: breakdown.competition_pressure, trend: trends.competition_trend },
            { icon: BarChart3, label: 'Confidence', value: breakdown.investor_confidence, trend: null },
            { icon: AlertTriangle, label: 'Risk', value: breakdown.market_risk, trend: null },
          ].map((item, i) => (
            <div key={i} className="neo-panel p-5">
              <div className="flex items-center gap-2 mb-2">
                <item.icon size={14} className="text-text-faint" />
                <span className="text-[10px] font-mono text-text-faint uppercase">{item.label}</span>
              </div>
              <div className="text-lg font-semibold">{item.value || 'N/A'}</div>
              {item.trend && (
                <div className="flex items-center gap-1 mt-1 text-xs text-text-muted">
                  <TrendIcon trend={item.trend} />
                  {item.trend}
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Market Context */}
        <div className="neo-panel p-6 mb-8">
          <h2 className="text-sm font-mono text-text-faint uppercase tracking-wider mb-4">Market Context</h2>
          <p className="text-sm text-text-muted leading-relaxed mb-4">{market.summary || 'No market summary available.'}</p>
          {(market.key_events || []).length > 0 && (
            <div className="space-y-2">
              <h3 className="text-xs font-mono text-text-faint uppercase">Key Events</h3>
              {market.key_events.map((e, i) => (
                <div key={i} className="flex items-start gap-2 text-sm text-text-muted">
                  <span className="text-primary-light mt-1">•</span>
                  {e}
                </div>
              ))}
            </div>
          )}
          {market.sources_used && (
            <div className="mt-4 text-[10px] font-mono text-text-faint">
              SOURCES: {(market.sources_used || []).join(', ')}
            </div>
          )}
        </div>

        {/* Recommendation */}
        <div className="glass-card p-6 border border-success/20 mb-8">
          <h2 className="text-sm font-mono text-success uppercase tracking-wider mb-4">Strategic Recommendation</h2>
          <div className="grid grid-cols-3 gap-4 mb-4">
            <div>
              <div className="text-[10px] font-mono text-text-faint uppercase">Strategy</div>
              <div className="text-sm font-medium mt-1">{recommendation.recommendation_type?.replace(/_/g, ' ') || 'N/A'}</div>
            </div>
            <div>
              <div className="text-[10px] font-mono text-text-faint uppercase">Best Price</div>
              <div className="text-sm font-medium mt-1 font-mono">₹{recommendation.best_price || '—'}</div>
            </div>
            <div>
              <div className="text-[10px] font-mono text-text-faint uppercase">Score Gain</div>
              <div className="text-sm font-medium mt-1 text-success">+{recommendation.score_improvement || 0} pts</div>
            </div>
          </div>
          <p className="text-sm text-text-muted leading-relaxed">{recommendation.strategic_advice}</p>

          {/* Comparison Table */}
          {(recommendation.comparison_table || []).length > 0 && (
            <div className="mt-6">
              <h3 className="text-xs font-mono text-text-faint uppercase mb-3">Price Comparison</h3>
              <div className="overflow-hidden rounded-lg border border-border">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-surface-raised text-text-faint text-[10px] font-mono uppercase">
                      <th className="px-4 py-2.5 text-left">Price</th>
                      <th className="px-4 py-2.5 text-left">Score</th>
                      <th className="px-4 py-2.5 text-left">Label</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border">
                    {recommendation.comparison_table.map((row, i) => (
                      <tr key={i} className={row.label?.includes('BEST') ? 'bg-success/5' : ''}>
                        <td className="px-4 py-2.5 font-mono">₹{row.price}</td>
                        <td className="px-4 py-2.5 font-mono">{row.score}/100</td>
                        <td className="px-4 py-2.5">
                          {row.label?.includes('BEST') ? (
                            <span className="px-2 py-0.5 rounded bg-success/20 text-success text-xs font-mono">{row.label}</span>
                          ) : (
                            <span className="text-text-muted">{row.label}</span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>

        {/* Agent Timeline */}
        <div className="neo-panel p-6 mb-8">
          <h2 className="text-sm font-mono text-text-faint uppercase tracking-wider mb-4">Agent Decision Timeline</h2>
          <div className="space-y-4">
            {(agentLogs || []).map((log, i) => {
              const step = log.step || i + 1;
              const stepState = history[i] || {};
              return (
                <div key={i} className="flex gap-4">
                  <div className="flex flex-col items-center">
                    <div className="w-8 h-8 rounded-full border border-border bg-surface-raised flex items-center justify-center text-xs font-mono text-text-muted">
                      {step}
                    </div>
                    {i < agentLogs.length - 1 && <div className="w-px flex-1 bg-border mt-1" />}
                  </div>
                  <div className="flex-1 pb-4">
                    <div className="text-xs font-mono text-text-faint mb-2">STEP {step}</div>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
                      <div className="bg-surface-raised rounded-md p-3 border border-border">
                        <div className="text-[10px] font-mono text-accent-cyan uppercase">Customer</div>
                        <div className="text-xs text-text-muted mt-1">{log.customer?.sentiment || 'neutral'}</div>
                        <div className="text-[10px] text-text-faint mt-0.5">Demand: {stepState.demand != null ? `${(stepState.demand * 100).toFixed(0)}%` : '—'}</div>
                      </div>
                      <div className="bg-surface-raised rounded-md p-3 border border-border">
                        <div className="text-[10px] font-mono text-warning uppercase">Competitor</div>
                        <div className="text-xs text-text-muted mt-1">{log.competitor?.strategy || 'monitoring'}</div>
                        <div className="text-[10px] text-text-faint mt-0.5">Action: {log.competitor?.action || 'none'}</div>
                      </div>
                      <div className="bg-surface-raised rounded-md p-3 border border-border">
                        <div className="text-[10px] font-mono text-primary-light uppercase">Investor</div>
                        <div className="text-xs text-text-muted mt-1">{log.investor?.verdict || 'hold'}</div>
                        <div className="text-[10px] text-text-faint mt-0.5">Confidence: {stepState.confidence != null ? `${(stepState.confidence * 100).toFixed(0)}%` : '—'}</div>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Footer */}
        <div className="text-center py-8 text-[10px] font-mono text-text-faint">
          VYUHA-MIND ENGINE v2.0 • ANALYST POST-MORTEM • {new Date().toLocaleString()}
        </div>
      </div>
    </div>
  );
}
